name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    
    steps:
    - name: Checkout homebrew-glug
      uses: actions/checkout@v5
      with:
        repository: d0ugal/homebrew-glug
        token: ${{ secrets.GITHUB_TOKEN }}
        path: homebrew-glug

    - name: Get release info
      id: release
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        VERSION=${TAG_NAME#v}  # Remove 'v' prefix
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Get SHA256 hash
      id: sha256
      run: |
        TAG_NAME="${{ steps.release.outputs.tag_name }}"
        SHA256=$(curl -L "https://github.com/d0ugal/glug/archive/${TAG_NAME}.tar.gz" | shasum -a 256 | cut -d' ' -f1)
        echo "sha256=$SHA256" >> $GITHUB_OUTPUT

    - name: Update formula
      run: |
        VERSION="${{ steps.release.outputs.version }}"
        TAG_NAME="${{ steps.release.outputs.tag_name }}"
        SHA256="${{ steps.sha256.outputs.sha256 }}"
        
        # Update the formula file
        sed -i "s|url \".*\"|url \"https://github.com/d0ugal/glug/archive/${TAG_NAME}.tar.gz\"|" homebrew-glug/Formula/glug.rb
        sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" homebrew-glug/Formula/glug.rb

    - name: Commit and push changes
      run: |
        cd homebrew-glug
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/glug.rb
        git commit -m "Update glug to ${{ steps.release.outputs.tag_name }}"
        git push
